apiVersion: v1
kind: Service
metadata:
  name: bitbucket-service
  namespace: bitns
spec:
  type: NodePort      
  selector:
    app: bitbucket
  ports:
    - name: bitbucket-http
      protocol: TCP
      port: 7990
      targetPort: 7990
      nodePort: 30234  
    - name: bitbucket-ssh
      protocol: TCP
      port: 7999
      targetPort: 7999
      nodePort: 30023 

