apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.depname }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.maxsurge }}
      maxUnavailable: {{ .Values.maxunavailable }}
  selector: 
    matchLabels:
      app: {{ .Values.label }}
  template:
    metadata:
      name: {{ .Values.metadataname }}
      labels:
        app: {{ .Values.label }}
    spec:
      containers:
        - name: {{ .Values.containername }}
          image: {{ .values.imagename }}:{{ .Values.tagname }}
