apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serv_name }}
  namespace: {{ .Values.namespace }}
spec:
  selector: 
    app: {{ .Values.label }}
  ports: 
    - name: {{ .Values.portname }}
      protocol: TCP
      port: {{ .Values.portno }}
      targetPort: {{ .Values.targetport }}
